### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by marlonmarcello**
Initiating the pull request for @andrewrubin as I need to speed this up.
@liamegan please give your thoughts on this as soon as you can.

### CODE REVIEW

**Comment by marlonmarcello** [comment]
I like the simplicity of this both the styles and the way the modal operates. I have only one thought.

With es6 import/export I am seeing libraries and frameworks move away from classes in favour of simple functions. With smaller functions we can import only what we need, reducing bundling size considerably and also bundlers like wepback and rollup can optimize the final output even more by doing tree shaking.
https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/

As this class is a singleton, I think it's a great use case for a more functional approach. We would be able to avoid importing the whole class every time we need a modal.
We would just import the `open` function, which if small enough, webpack will append the function to the bundle to avoid a call to the external file.

Let me know what you guys think.

**Comment by andrewrubin** [comment]
I like the idea of importing only the functions we need as opposed to the whole class, for sure. Even though it's a small class, every little bit of bundle savings counts in the end. I can make these changes if we are all in agreement.

**Comment by liamegan** [comment]
Has this update been tested in production anywhere yet?

**Comment by andrewrubin** [comment]
It has not been tested in production… Just the example directory in this branch, and this CodePen project (which is essentially the same, just using a module import statement, and some different markup) https://codepen.io/andyranged/project/editor/ace558233d7d636a5b3be8965a7fb510

**Comment by liamegan** [comment]
Ok, well I'm good with this merge then. Given the changes let's bump the minor version.

Regarding import / export using functional style, I'm good with that. We should talk about what this means in a larger context as well.

**Pull request merged**
