### PR TITLE
Removing singleton aspect of modal

### PR DESCRIPTION
**Pull request by marlonmarcello**
### Problem
The modal was a singleton, leaving us unable to have multiple modals or "modalception" in a page.

### Solution
Turned the modal into a regular class.

#### Summary of changes
Modal is now a regular class
Updated docs
Bumped version to 2.0 as this is a breaking change

### CODE REVIEW

**Comment by marlonmarcello** [comment]
As per our conversation I updated it to use `getters` and `setters`

**Review by andrewrubin — COMMENTED** [review]
This is excellent. As we talked about, let's either clear out the modalContent on close, or toggle display none/block on open/close. I think maybe the latter? Just because even if the content is cleared out, the close button is still focusable. Whaddaya think @marlonmarcello

**Comment by marlonmarcello** [comment]
@andrewrubin wouldn't setting display none kill our animation?
Should I do that on the close button only?

**Comment by marlonmarcello** [comment]
@andrewrubin updates are up

**Comment by marlonmarcello** [comment]
Pushed an update to fix the focus order.

**Comment by andrewrubin** [comment]
Looks awesome @marlonmarcello !!
I have one concern:

### Scenario:
- You're in a modal where the **content** contains no focusable items (as in example 1 on the sample HTML file)
- the paragraph is focused onOpen (awesome)
- you tab **backwards** and the close button is focused (awesome)
- you tab backwards _again_ and the paragraph is focused ***

*** I think the paragraph should not be focusable, aside from the initial onOpen, since it's not a focusable element.

### Suggestion:
I think we should re-write `focusLastElement` so that it queries only focusable elements. Something like:
```js
const focusableElements = this.modalContent.querySelectorAll("[href], button");
const lastFocusableElement = focusableElements[focusableElements.length - 1];
lastFocusableElement.focus();
```

What do you think about this?

**Comment by marlonmarcello** [comment]
@andrewrubin what happens if it doesn't find anything?
Just keep the focus on the close button?

**Comment by andrewrubin** [comment]
Yeah, exactly. @marlonmarcello

**Comment by marlonmarcello** [comment]
@andrewrubin Done!

**Comment by andrewrubin** [comment]
Amazing. Let's merge this thing!

**Review by andrewrubin — APPROVED** [review]

**Review by liamegan — APPROVED** [review]
This all looks great to me. We'll probably want to update the class to use form values for some things at some point in the future, but this works well as is.

**Comment by liamegan** [comment]
@marlonmarcello I fixed the conflict on this. Please feel free to merge whenever.

**Comment by marlonmarcello** [comment]
Will publish to NPM now.
Thanks guys! Thanks @andrewrubin for all the feedback

**Pull request merged**
